version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: clube-quinze-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: clube_quinze
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: clube-quinze-api
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.example
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/clube_quinze
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: prod
    command: ["sh", "-c", "java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE:-prod} -jar /app/app.jar"]

volumes:
  postgres_data:
